version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - 3000
    volumes:
      - .:/workspace
      - /workspace/node_modules
    command: /bin/sh -c "npm run build;while sleep 1000; do :; done" 
